import { ClerkProvider } from '@clerk/nextjs';
import { type AppType } from 'next/app';
import Head from 'next/head';
import '~/styles/globals.css';
import { api } from '~/utils/api';

const MyApp: AppType = ({ Component, pageProps }) => (
  <ClerkProvider {...pageProps}>
    <Head>
      <title>Vogel</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </ClerkProvider>
);

export default api.withTRPC(MyApp);
