import { SignInButton, useUser } from '@clerk/nextjs';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { type NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { LoadingSpinner } from '~/components/loading-spinner';
import { api, type RouterOutputs } from '~/utils/api';

dayjs.extend(relativeTime);

const FeedHeader = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.profileImageUrl}
        height={60}
        width={60}
        alt="Profile"
        className="rounded-full"
      />
      <input
        placeholder="What's Happening? 🦃 🐓 🦆"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs['posts']['getAll'][number];
type PostProps = { postWithUser: PostWithUser };
const PostView = ({
  postWithUser: {
    post: { id, content, createdAt },
    author: { username, profileImageUrl },
  },
}: PostProps) => {
  const atUsername = `@${username}`;
  return (
    <div className="flex gap-3 border-b border-slate-400 p-4" key={id}>
      <Image
        src={profileImageUrl}
        alt={`${atUsername}'s profile`}
        height={60}
        width={60}
        className="rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex gap-2 text-slate-300">
          <span>{atUsername}</span>
          <span>·</span>
          <span className="font-thin">{dayjs(createdAt).fromNow()}</span>
        </div>
        <span>{content}</span>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { data: posts, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if (isLoading) {
    return <LoadingSpinner />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-200 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {user.isSignedIn ? <FeedHeader /> : <SignInButton />}
          </div>
          <div className="flex flex-col">
            {posts?.map((postWithUser) => (
              <PostView
                key={postWithUser.post.id}
                postWithUser={postWithUser}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
